version: "3"
services:
  frontend:
    container_name: frontend_container
    build: ./frontend
    depends_on:
      - backend
    ports: 
      - 80:8080
    networks:
      - network-backend

  backend:
    container_name: backend_container
    build: ./backend
    depends_on:
      - db
    ports: 
      - 3000:3000
    networks:
      - network-backend

  db:
    container_name: db_container
    build: ./db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf  # MySQL 설정 바인딩
      - ./db/init_db:/docker-entrypoint-initdb.d      # 초기 데이터 투입용 sql 바인딩
      - db_data:/var/lib/mysql                      # 영속화 데이터 바인딩
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}              # set mysql info
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - network-backend

networks:
  network-backend:

volumes:
  db_data:

