version: "3"

services:
  frontend:
    image: node
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
      # - ./html:/usr/share/nginx/html
      - ./html:/usr/share/nginx/html
