version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx-deploy.conf:/etc/nginx/conf.d/default.conf
      # - ./html:/usr/share/nginx/html
      - ./html:/usr/share/nginx/html
